Hexlet/hexlet-correction

pom.xml
src/main/java/io/hexlet/hexletcorrection/controller/api/v1/AccountController.java
src/main/java/io/hexlet/hexletcorrection/controller/api/v1/CorrectionController.java
src/main/java/io/hexlet/hexletcorrection/dto/AccountDto.java
src/main/java/io/hexlet/hexletcorrection/dto/AccountPostDto.java
src/main/java/io/hexlet/hexletcorrection/dto/CorrectionDto.java
src/main/java/io/hexlet/hexletcorrection/dto/CorrectionPostDto.java
src/main/java/io/hexlet/hexletcorrection/dto/mapper/AccountMapper.java
src/main/java/io/hexlet/hexletcorrection/dto/mapper/CorrectionMapper.java
src/test/java/io/hexlet/hexletcorrection/dto/mapper/AccountMapperTest.java
src/test/java/io/hexlet/hexletcorrection/dto/mapper/CorrectionMapperTest.java

Созданы DTO для API сущностей. Настроен маппинг сущностей в DTO и обратно.
Дополнительно fixed #15

Added DTOs for API entities and mapping

---

src/main/java/io/hexlet/hexletcorrection/config/LocaleConfig.java
src/main/resources/messages.properties
src/main/resources/messages_en.properties
src/main/resources/templates/fragments/footer.html
src/main/resources/templates/fragments/head-styles.html
src/main/resources/templates/fragments/header.html
src/main/resources/templates/index.html
src/main/resources/templates/login.html
src/main/resources/templates/registration.html

Добавил интернационализацию.
Обновил футер как в HexletCV.
Поправил синтаксис thymeleaf.

Added i18n. Update footer.

---

src/main/java/io/hexlet/hexletcorrection/config/WebSecurityConfig.java
src/test/java/io/hexlet/hexletcorrection/SwaggerTest.java

Добавил `/swagger-ui.html` в исключения security.
Пофиксил переключение языка на странице логина.

Fixed security

---

src/main/java/io/hexlet/hexletcorrection/config/WebSecurityConfig.java
src/main/java/io/hexlet/hexletcorrection/service/impl/UserDetailsServiceImpl.java
src/main/resources/messages.properties

Пофиксил вход. Роль должна быть без префикса `ROLE_`.
Добавил ресурсы swagger-ui в исключения security.

Fixed login and swagger-ui resources security ignore

---

CONTRIBUTING.md
README.md

Добавил информацию о том, как контрибютить в проект.

Added contributing info

---

src/main/java/io/hexlet/hexletcorrection/controller/AccountControllerStatic.java
src/main/java/io/hexlet/hexletcorrection/dto/mapper/AccountMapper.java
src/main/java/io/hexlet/hexletcorrection/service/impl/AccountServiceImpl.java
src/main/resources/messages.properties
src/main/resources/messages_en.properties
src/main/resources/templates/account/edit.html
src/main/resources/templates/account/list.html
src/main/resources/templates/account/new.html
src/main/resources/templates/account/view.html
src/main/resources/templates/fragments/head-styles.html
src/main/resources/templates/fragments/header.html
src/main/resources/templates/fragments/simple-head.html
src/main/resources/templates/index.html
src/test/java/io/hexlet/hexletcorrection/controller/AbstractControllerTest.java
src/test/java/io/hexlet/hexletcorrection/controller/AccountControllerStaticTest.java
src/test/java/io/hexlet/hexletcorrection/controller/FrontendTest.java
src/test/java/io/hexlet/hexletcorrection/dto/mapper/AccountMapperTest.java

Создал другую, ветку, удалил секюрити. Пока не надо мержить так-как я еще сюда тесты не добавил, но увидеть уже можно сейчас как оно будет.

add-thymeleaf-template-for-accounts

---

.jhipster/Comment.json
.jhipster/Correction.json
.jhipster/Preference.json
.jhipster/modules/jhi-hooks.json
.yo-rc.json
package-lock.json
package.json
pom.xml
src/main/java/io/hexlet/hexletcorrection/config/audit/EntityAuditAction.java
src/main/java/io/hexlet/hexletcorrection/config/audit/JaversAuthorProvider.java
src/main/java/io/hexlet/hexletcorrection/domain/AbstractAuditingEntity.java
src/main/java/io/hexlet/hexletcorrection/domain/Comment.java
src/main/java/io/hexlet/hexletcorrection/domain/Correction.java
src/main/java/io/hexlet/hexletcorrection/domain/EntityAuditEvent.java
src/main/java/io/hexlet/hexletcorrection/domain/Preference.java
src/main/java/io/hexlet/hexletcorrection/repository/CommentRepository.java
src/main/java/io/hexlet/hexletcorrection/repository/CorrectionRepository.java
src/main/java/io/hexlet/hexletcorrection/repository/PreferenceRepository.java
src/main/java/io/hexlet/hexletcorrection/service/dto/AbstractAuditingDTO.java
src/main/java/io/hexlet/hexletcorrection/service/dto/CommentDTO.java
src/main/java/io/hexlet/hexletcorrection/service/dto/CorrectionDTO.java
src/main/java/io/hexlet/hexletcorrection/service/dto/PreferenceDTO.java
src/main/java/io/hexlet/hexletcorrection/web/rest/JaversEntityAuditResource.java
src/main/resources/config/liquibase/changelog/20200303140657_added_entity_Preference.xml
src/main/resources/config/liquibase/changelog/20200303140757_added_entity_Correction.xml
src/main/resources/config/liquibase/changelog/20200303140857_added_entity_Comment.xml
src/main/webapp/i18n/en/entity-audit.json
src/main/webapp/i18n/en/global.json
src/main/webapp/i18n/ru/entity-audit.json
src/main/webapp/i18n/ru/global.json

Change-Id: I875a5a9e1d836297b983ae01a15e5e21c6063d9f

add entities audit with Javers

---

src/main/webapp/app/entities/correction/correction.tsx

remake-Corrections

---

Makefile
src/main/java/io/hexlet/typoreporter/domain/account/Account.java
src/main/java/io/hexlet/typoreporter/domain/account/AuthProvider.java
src/main/java/io/hexlet/typoreporter/domain/account/AuthProviderPgEnum.java
src/main/java/io/hexlet/typoreporter/domain/account/constraint/AccountUsername.java
src/main/java/io/hexlet/typoreporter/domain/typo/Typo.java
src/main/java/io/hexlet/typoreporter/domain/workspace/Workspace.java
src/main/java/io/hexlet/typoreporter/repository/AccountRepository.java
src/main/resources/config/application-dev.yml
src/main/resources/db/changelog/changesets/2022/04/20220428163604-create-account-table.xml
src/main/resources/db/changelog/db.changelog-master.xml
src/test/java/io/hexlet/typoreporter/domain/EntityTest.java
src/test/java/io/hexlet/typoreporter/repository/AccountRepositoryIT.java
src/test/java/io/hexlet/typoreporter/service/converter/CreateWorkspaceToWorkspaceTest.java
src/test/java/io/hexlet/typoreporter/test/DBUnitEnumPostgres.java
src/test/java/io/hexlet/typoreporter/test/asserts/TypoAssert.java
src/test/java/io/hexlet/typoreporter/test/factory/EntitiesFactory.java
src/test/resources/datasets/accounts.yml

add Account entity with relations
edit Typo|Workspace
add AccountRepository with findByEmail
add changeset
edit changelog

[#87] add account

---

src/main/java/io/hexlet/typoreporter/domain/workspace/Workspace.java
src/main/java/io/hexlet/typoreporter/repository/AccountRepository.java
src/main/java/io/hexlet/typoreporter/web/Routers.java
src/main/java/io/hexlet/typoreporter/web/Templates.java
src/main/java/io/hexlet/typoreporter/web/WorkspaceController.java
src/main/resources/templates/fragments/panels.html
src/main/resources/templates/index.html
src/main/resources/templates/workspace/wks-users.html
src/test/java/io/hexlet/typoreporter/repository/AccountRepositoryIT.java
src/test/java/io/hexlet/typoreporter/web/WorkspaceControllerIT.java

Added wks-users.html, links in side bar and index.html
Added handler for "workspace/{wks-name}/users" endpoint
Added constants USERS and WKS_USERS_TEMPLATE
Added methods in Workspace class for add/remove accounts
Added method in accountRepository for getting page by WKS-NAME
Added tests for workspaceController and accountRepository.

#106 Add page list of all users

---

.github/ISSUE_TEMPLATE/bugreport.yml
.github/ISSUE_TEMPLATE/featureRequest.yml
.github/ISSUE_TEMPLATE/task.yml

Three issue templates were added

Added issue templates

---

Makefile
src/main/java/io/hexlet/typoreporter/domain/account/Account.java
src/main/java/io/hexlet/typoreporter/domain/workspace/AccountRole.java
src/main/java/io/hexlet/typoreporter/domain/workspace/Workspace.java
src/main/java/io/hexlet/typoreporter/domain/workspace/WorkspaceRole.java
src/main/java/io/hexlet/typoreporter/domain/workspace/WorkspaceRoleId.java
src/main/java/io/hexlet/typoreporter/repository/WorkspaceRepository.java
src/main/java/io/hexlet/typoreporter/repository/WorkspaceRoleRepository.java
src/main/java/io/hexlet/typoreporter/service/WorkspaceRoleService.java
src/main/java/io/hexlet/typoreporter/service/WorkspaceService.java
src/main/java/io/hexlet/typoreporter/web/Routers.java
src/main/java/io/hexlet/typoreporter/web/WorkspaceController.java
src/main/java/io/hexlet/typoreporter/web/exception/AccountNotFoundException.java
src/main/resources/db/changelog/changesets/2022/12/2022-12-01-add-workspace_role-table.xml
src/main/resources/db/changelog/db.changelog-master.xml
src/main/resources/templates/workspace/wks-users.html
src/test/java/io/hexlet/typoreporter/repository/AccountRepositoryIT.java
src/test/java/io/hexlet/typoreporter/service/converter/CreateWorkspaceToWorkspaceTest.java
src/test/java/io/hexlet/typoreporter/web/WorkspaceControllerIT.java

Changed the relationship between the account and the workspace on ManyToMany using.
Added functionality for adding an account.

Add workspace role

---

src/main/java/io/hexlet/typoreporter/domain/account/Account.java
src/main/java/io/hexlet/typoreporter/repository/AccountRepository.java
src/main/java/io/hexlet/typoreporter/repository/WorkspaceRoleRepository.java
src/main/java/io/hexlet/typoreporter/service/AccountService.java
src/main/java/io/hexlet/typoreporter/service/dto/workspace/WorkspaceRoleInfo.java
src/main/java/io/hexlet/typoreporter/service/mapper/WorkspaceRoleMapper.java
src/main/java/io/hexlet/typoreporter/web/AccountController.java
src/main/resources/db/changelog/changesets/2023/02/2023-20-02-remove-many-to-one-account-workspace-relation.xml
src/main/resources/db/changelog/db.changelog-master.xml
src/main/resources/templates/account/acc-info.html
src/test/java/io/hexlet/typoreporter/repository/AccountRepositoryIT.java
src/test/java/io/hexlet/typoreporter/repository/WorkspaceRoleRepositoryIT.java
src/test/java/io/hexlet/typoreporter/test/factory/EntitiesFactory.java
src/test/resources/datasets/workspaceRoles.yml

* Удален параметр workspace из сущности Account
* Добавлена миграция на удаление параметра вместе со связью в таблице бд account
* Обновлены AccountService и AccountController  в местах, где формировалась инфа об аккаунте
* Обновлён шаблон вывода инфы об аккаунте
* Удален неиспользуемый более тест

fix #130 remove many to one account-workspace relation

---

src/main/java/io/hexlet/typoreporter/domain/account/Account.java
src/main/java/io/hexlet/typoreporter/domain/workspace/Workspace.java
src/main/java/io/hexlet/typoreporter/domain/workspace/WorkspaceRole.java
src/main/java/io/hexlet/typoreporter/repository/WorkspaceRepository.java
src/main/java/io/hexlet/typoreporter/service/WorkspaceService.java
src/main/java/io/hexlet/typoreporter/web/IndexController.java
src/main/java/io/hexlet/typoreporter/web/WorkspaceController.java
src/test/java/io/hexlet/typoreporter/service/WorkspaceServiceIT.java
src/test/java/io/hexlet/typoreporter/service/mapper/CreateWorkspaceToWorkspaceTest.java
src/test/java/io/hexlet/typoreporter/web/WorkspaceControllerIT.java

The account gets role_admin when it is created. Moving to the service.

account gets role_admin when created workspace in service

---

src/widget/index.html
src/widget/index.js

Add the ability to change workSpaceUrl and api token.

---

src/main/java/io/hexlet/typoreporter/web/WorkspaceApi.java
src/main/java/io/hexlet/typoreporter/web/WorkspaceSettingsController.java
src/main/resources/templates/workspace/wks-settings.html
src/test/java/io/hexlet/typoreporter/web/WorkspaceApiIT.java

1. Добавила в урл id workspace
2. Обновила тесты
3. На всякий случай обновила урл в workspace settings

fix #140 fixed path to send typos

---

src/widget/index.html
src/widget/index.js

На данный момент поправлен текст в кнопках и исправлен баг с множественной отправкой на сервер.

Fix bugs in typo widget

---

src/main/java/io/hexlet/typoreporter/config/CustomAccessDeniedHandler.java
src/main/java/io/hexlet/typoreporter/config/SecurityConfig.java
src/main/java/io/hexlet/typoreporter/service/WorkspaceService.java
src/main/java/io/hexlet/typoreporter/web/IndexController.java
src/main/java/io/hexlet/typoreporter/web/WorkspaceController.java
src/test/java/io/hexlet/typoreporter/test/factory/EntitiesFactory.java
src/test/java/io/hexlet/typoreporter/web/WorkspaceControllerIT.java

Task #147 
Демонстрация: https://hexlet-corrector-fork.onrender.com/workspaces

Show only related to user workspaces

---

src/main/resources/templates/login.html

Добавила на страницу логина ссылку на регистрацию
https://hexlet-correction-add-signup-to-loginpage.up.railway.app/

added signup link

---

src/main/resources/templates/workspace/wks-settings.html

Added form to copy widget. In result page looks like this: https://disk.yandex.com/i/12Xu2P6SPNh48A

Added form to copy widget

---

.tool-versions
src/main/resources/templates/workspace/wks-settings.html

был неверный скрипт (без кавычек и импорта).

Fix widget form

---

src/main/java/io/hexlet/typoreporter/web/WorkspaceController.java

Было: _/workspace/{wksName}/users/_
Стало: _/workspace/{wksName}/users_

[#162] Исправлен адрес редиректа

---

src/main/java/io/hexlet/typoreporter/service/WorkspaceService.java
src/main/java/io/hexlet/typoreporter/web/WorkspaceController.java
src/main/resources/templates/workspace/wks-update.html
src/test/java/io/hexlet/typoreporter/service/WorkspaceServiceIT.java
src/test/java/io/hexlet/typoreporter/web/WorkspaceControllerIT.java

Добавил возможность редактирования url воркспейса. При редактировании учитываем, что по переданному url отсутствуют другие воркспейсы с аналогичным url (сделано аналогично имени воркспейса)
Форма:

Issue165 - Редактирование url воркспейса

---

src/main/resources/templates/workspace/wks-settings.html

https://github.com/Hexlet/hexlet-correction/issues/212
Сделал поля с данными для интеграции удобнее

[#212] Fix integration fields view

---

README.md

Fixes #207
Add {workspaceId} placeholder to the POST sample.

Update POST request sample in README

---

src/main/resources/templates/index.html

[Issue 173](https://github.com/Hexlet/hexlet-correction/issues/173) - поправил хедер на главной странице:

[#173] Fix main page header

---

src/widget/index.js

Исправила проблему. Теперь при увеличенном масштабе окна появляется скроллбар, при этом скроллбар страницы сайта пропадает.

[#210] fix(widget): fix site and modal overflow behavior

---

Makefile
src/main/java/io/hexlet/typoreporter/service/WorkspaceRoleService.java
src/main/java/io/hexlet/typoreporter/utils/ValidationEmail.java
src/main/java/io/hexlet/typoreporter/web/WorkspaceController.java
src/main/java/io/hexlet/typoreporter/web/model/WorkspaceUserModel.java
src/main/resources/templates/workspace/wks-users.html

fix bug #203 
replace dropdown list to input

fix bug #203

---

src/main/java/io/hexlet/typoreporter/controller/TypoController.java
src/main/resources/templates/workspace/wks-typos.html
src/test/java/io/hexlet/typoreporter/web/TypoControllerIT.java

https://hexlet-correction-5968.onrender.com/
Login: bb@bb.ru
pass: Aa123456

[#208] add param next for redirect with filters on TypoController

---

src/main/resources/templates/workspace/wks-typos.html

[#251] Add the style block for class="btn-group" and add the margin on 5px.

---

src/widget/index.js

Исправил ошибку, при которой была возможность репортить содержимое виджета

[#248] FIX index.js

---

src/main/resources/templates/workspace/wks-users.html

[#255] Strip out unnecessary elements from the page

---

src/main/resources/templates/fragments/footer.html

Поменял в футере ссылку и название

[#274] fix bug with link on main page

---

src/main/resources/templates/workspace/wks-integration.html
src/widget/index.html
src/widget/index.js

Added a timestamp query parameter to the script URL to force browsers to load the latest version of the script

rework the script connection #283

---

src/main/resources/templates/workspace/wks-integration.html
src/widget/index.js

Fixed last pull request errors.

update rework the script connection - use greedy loading #283

---

src/widget/index.js

Removed the block that was responsible for the unnecessary line asking about sending an error report.

[#247] Removed element with the question from error report

---

src/main/resources/templates/workspace/wks-typos.html

This issue is fixed. See screenshot. Here is the link to the deployed app https://hexlet-correction-2.onrender.com/.

Fix issue #191 long url breaks layout

---

src/main/resources/templates/fragments/panels.html

Removed link from user email in navbar and added new classes to keep the styling

[#305] Removed link from user email

---

src/main/resources/messages_en.properties
src/main/resources/messages_ru.properties
src/main/resources/templates/fragments/panels.html

**What has been done:**
- Added a "Workspaces" button to the navigation header.
- Clicking the button redirects users to the list of their workspaces.
**How to test:**
- Log in to the application.
- Ensure the "Workspaces" button is visible in the navigation header.
- Click the button and verify it redirects to the workspaces list page.
**Related Issues:**
Issue #307

[#307] Add link to workspaces button in header

---

.github/workflows/pages.yml
README.md

должно сработать)
по крайне мере, у меня action пункт set up job успешно прошел

Fix-pipeline-328
