Hexlet/hexlet-correction

- pom.xml
- src/main/java/io/hexlet/typoreporter/config/thymeleaf/ThymeleafAutoConfiguration.java
- src/main/java/io/hexlet/typoreporter/web/WorkspaceController.java
- src/main/resources/templates/workspace/wks-typos.html
> [#91] fix pagenation

- README.md
- src/main/java/io/hexlet/typoreporter/repository/WorkspaceRepository.java
- src/main/java/io/hexlet/typoreporter/service/WorkspaceService.java
- src/main/java/io/hexlet/typoreporter/service/converter/TypoToTypoInfoConverter.java
- src/main/java/io/hexlet/typoreporter/service/converter/WorkspaceToWorkspaceInfo.java
- src/main/java/io/hexlet/typoreporter/web/WorkspaceController.java
- src/test/java/io/hexlet/typoreporter/repository/WorkspaceRepositoryIT.java
- src/test/java/io/hexlet/typoreporter/service/WorkspaceServiceIT.java
- src/test/java/io/hexlet/typoreporter/service/converter/TypoToTypoInfoConverterTest.java
- src/test/java/io/hexlet/typoreporter/service/converter/WorkspaceToWorkspaceInfoTest.java
- src/test/java/io/hexlet/typoreporter/test/asserts/TypoInfoAssert.java
- src/test/java/io/hexlet/typoreporter/web/TypoControllerIT.java
- src/test/java/io/hexlet/typoreporter/web/WorkspaceControllerIT.java
Отправляю так: один коммит — один класс или пакет.
По завершению напишу сюда в комментариях.
> test: [#100] add tests for all TODO in repository/WorkspaceRepository

- src/main/java/io/hexlet/typoreporter/config/SecurityConfig.java
Теперь при переходе на страницу сервиса требуется авторизация.
https://hexlet-correction-dont-show-workspaces.up.railway.app/
Правильно ли я поняла задачу и нужно ли еще что-то добавить?
> fix #152 don't show workspaces page to unauthorized users

- src/main/resources/templates/workspaces.html
Fixed workspace cards height.
Height before:
Height after:
> [#181] fix workspace cards height

- src/main/java/io/hexlet/typoreporter/repository/TypoRepository.java
- src/main/java/io/hexlet/typoreporter/service/TypoService.java
- src/main/java/io/hexlet/typoreporter/web/WorkspaceController.java
- src/main/resources/messages_en.properties
- src/main/resources/messages_ru.properties
- src/main/resources/templates/fragments/panels.html
- src/main/resources/templates/workspace/wks-typos.html
- src/main/resources/templates/workspaces.html
- src/test/java/io/hexlet/typoreporter/test/factory/EntitiesFactory.java
- src/test/java/io/hexlet/typoreporter/web/WorkspaceControllerIT.java
[Issue 176](https://github.com/Hexlet/hexlet-correction/issues/176)
Добавил фильтрацию по статусу
Добавил тесты
Местами подправил локализацию
> Add status filtration

- src/main/resources/templates/workspace/wks-typos.html
https://github.com/Hexlet/hexlet-correction/issues/176
поправил отображение выпадающего списка (была проблема с пунктом IN_PROGRESS)
до:
после:
> [#176] Fix statuses dropdown

- src/main/resources/templates/workspace/wks-typos.html
https://github.com/Hexlet/hexlet-correction/issues/205
Демо: https://hexlet-correction-filtration.onrender.com/
Стрелка теперь стоит только у того столбца, по которому выполняется сортировка
> [#206] Fix sorting arrows

- src/main/resources/templates/workspace/wks-typos.html
https://github.com/Hexlet/hexlet-correction/issues/174
При добавлении опечатки, в столбце modifiedBy теперь пусто
> [#174] Fix modifiedBy initial view

- src/main/java/io/hexlet/typoreporter/domain/workspace/constraint/WorkspaceDescription.java
Fixes #213
Сделал поле "Описание пространства" необязательным. Убрал проверку на минимальное количество символов.
> Change workspace description validation rule

- src/main/java/io/hexlet/typoreporter/domain/AbstractAuditingEntity.java
- src/main/java/io/hexlet/typoreporter/repository/TypoRepository.java
- src/main/java/io/hexlet/typoreporter/service/TypoService.java
- src/main/java/io/hexlet/typoreporter/service/dto/typo/ReportedTypo.java
- src/main/java/io/hexlet/typoreporter/service/dto/typo/TypoInfo.java
- src/main/java/io/hexlet/typoreporter/service/dto/workspace/WorkspaceInfo.java
- src/main/java/io/hexlet/typoreporter/service/mapper/TypoMapper.java
- src/main/java/io/hexlet/typoreporter/service/mapper/WorkspaceMapper.java
- src/main/java/io/hexlet/typoreporter/web/WorkspaceController.java
- src/main/java/io/hexlet/typoreporter/web/WorkspaceSettingsController.java
- src/main/resources/db/changelog/changesets/2023/10/2023-10-16-change-time-format-to-timestamp-with-time-zone.xml
- src/main/resources/db/changelog/db.changelog-master.xml
- src/main/resources/messages_en.properties
- src/main/resources/messages_ru.properties
- src/main/resources/static/fragments/time-converter.js
- src/main/resources/templates/fragments/header.html
- src/main/resources/templates/fragments/workspace.html
- src/main/resources/templates/workspace/wks-info.html
- src/main/resources/templates/workspace/wks-typos.html
- src/test/java/io/hexlet/typoreporter/test/factory/EntitiesFactory.java
- src/test/java/io/hexlet/typoreporter/web/WorkspaceApiIT.java
- src/test/java/io/hexlet/typoreporter/web/WorkspaceControllerIT.java
Fixes #167 
1. Изменил тип даты/времени в коде с `LocalDateTime` на `Instant`, чтобы сделать привязку к UTC. Добавил миграцию, которая учитывает эти изменения. Все предыдущие записи дат приводятся в формат `TIMESTAMP WITH TIME ZONE` с часовым поясом UTC+00. Так как определить исходный часовой пояс этих записей невозможно, их точность снизится, зато новые записи будут точнее.
2. Дата отображается пользователям в их часовом поясе. Для этого добавил скрипт `time-converter.js` и поправил шаблоны. Если JS в браузере отключен, дата отобразится в формате UTC+00.
3. Сделал локализацию сообщений об относительном времени создания/изменения (`PrettyTime`).
4. Починил метод в `TypoRepository`, который возвращает последнюю добавленную опечатку (до этого он возвращал опечатку, добавленную первой). …
> Implement date localization, data type change, and TypoRepository fix (#167)

- src/main/java/io/hexlet/typoreporter/web/WorkspaceController.java
- src/main/java/io/hexlet/typoreporter/web/WorkspaceSettingsController.java
- src/main/resources/messages_en.properties
- src/main/resources/messages_ru.properties
- src/main/resources/templates/fragments/panels.html
- src/main/resources/templates/workspace/wks-integration.html
- src/main/resources/templates/workspace/wks-settings.html
- src/test/java/io/hexlet/typoreporter/test/factory/EntitiesFactory.java
- src/test/java/io/hexlet/typoreporter/web/WorkspaceSettingsControllerIT.java
Fixes #178 
Перенес модуль со скриптом во вкладку интеграции, также сделал кнопку регенерации токена видимой только для админа. Деплой по ссылке:
https://hexlet-correction-vasilyevps-fork.onrender.com/
Вкладка интеграция
Вкладка настройки (админ)
Вкладка настройки (юзер)
> Improve integration tab

- src/main/java/io/hexlet/typoreporter/config/SecurityConfig.java
- src/main/java/io/hexlet/typoreporter/repository/AccountRepository.java
- src/main/java/io/hexlet/typoreporter/repository/WorkspaceRoleRepository.java
- src/main/java/io/hexlet/typoreporter/security/service/AccountDetailService.java
- src/main/java/io/hexlet/typoreporter/service/AccountService.java
- src/main/java/io/hexlet/typoreporter/service/WorkspaceService.java
- src/main/java/io/hexlet/typoreporter/service/dto/AbstractFieldMatchValidator.java
- src/main/java/io/hexlet/typoreporter/service/dto/FieldMatchConsiderCase.java
- src/main/java/io/hexlet/typoreporter/service/dto/FieldMatchConsiderCaseValidator.java
- src/main/java/io/hexlet/typoreporter/service/dto/FieldMatchIgnoreCase.java
- src/main/java/io/hexlet/typoreporter/service/dto/FieldMatchIgnoreCaseValidator.java
- src/main/java/io/hexlet/typoreporter/service/dto/account/UpdatePassword.java
- src/main/java/io/hexlet/typoreporter/service/dto/account/UpdateProfile.java
- src/main/java/io/hexlet/typoreporter/web/AccountController.java
- src/main/java/io/hexlet/typoreporter/web/IndexController.java
- src/main/java/io/hexlet/typoreporter/web/SignupController.java
- src/main/java/io/hexlet/typoreporter/web/WorkspaceController.java
- src/main/java/io/hexlet/typoreporter/web/WorkspaceSettingsController.java
- src/main/java/io/hexlet/typoreporter/web/exception/AccountNotFoundException.java
- src/main/java/io/hexlet/typoreporter/web/model/SignupAccountModel.java
- src/main/resources/templates/login.html
- src/test/java/io/hexlet/typoreporter/repository/AccountRepositoryIT.java
- src/test/java/io/hexlet/typoreporter/repository/WorkspaceRoleRepositoryIT.java
- src/test/java/io/hexlet/typoreporter/test/factory/EntitiesFactory.java
- src/test/java/io/hexlet/typoreporter/web/AccountControllerIT.java
- src/test/java/io/hexlet/typoreporter/web/LoginIT.java
- src/test/java/io/hexlet/typoreporter/web/SignupControllerIT.java
- src/test/java/io/hexlet/typoreporter/web/WorkspaceControllerIT.java
- src/test/java/io/hexlet/typoreporter/web/WorkspaceSettingsControllerIT.java
Авторизация по почте вместо имени пользователя теперь выполняется.
При регистрации нового юзера, входе в систему и смене пароля у юзера теперь не учитывается регистр символов в email. Тесты на это запилил.
Шаблончик страницы ввода логина/пароля тоже поправил.
> Авторизация по почте вместо имени пользователя

- src/main/java/io/hexlet/typoreporter/service/dto/FieldMatchConsiderCase.java
- src/main/java/io/hexlet/typoreporter/service/dto/FieldMatchIgnoreCase.java
- src/main/java/io/hexlet/typoreporter/service/dto/account/UpdateProfile.java
- src/main/java/io/hexlet/typoreporter/web/model/SignupAccountModel.java
- src/main/resources/templates/account/prof-update.html
- src/main/resources/templates/account/signup.html
- src/test/java/io/hexlet/typoreporter/web/AccountControllerIT.java
- src/test/java/io/hexlet/typoreporter/web/LoginIT.java
- src/test/java/io/hexlet/typoreporter/web/SignupControllerIT.java
Подтверждение почты убрал.
Тесты подправил.
Потыкать можно [тут](https://hexlet-correction-r29m.onrender.com/signup?lang=en).
> Убрать подтверждение почты при регистрации и изменении аккаунта

- src/widget/index.js
Исправлен баг, упомянутый тут: https://github.com/Hexlet/hexlet-correction/issues/245
Выполняется проверка на то, выполнено выделение наоборот или нет и в зависимости от этого вычисляется текст до и текст после
> [#245] Fix reverse selection bug

- src/widget/index.js
Показалось, что более интуитивно и симпатично будет выглядеть подсвечивание опечатки в фрагменте так же, как это выглядит, когда ты просто выделяешь текст
Before:
After:
> Update widget's typo selection appearance

- src/widget/index.js
Обнаружил баг, который проявлялся только при определённом количестве выделенных символов и положении выделения относительно параграфа:
Проблема была в том, что в зависимости от направления выделения, иначе высчитывать нужно также и start вместе с end. Правлю свои же недочёты :)
> Fix widget selection algorithm

- src/main/resources/templates/workspace/wks-users.html
A bugfix for issue [#259](https://github.com/Hexlet/hexlet-correction/issues/259). 
Deleted second hidden not-working Delete button for users in workspace. Also cleaned all parameters regarding accordeon/collapsed from parent tag.
> Delete non-admin user deletion button in workspace

- src/main/resources/messages_en.properties
- src/main/resources/messages_ru.properties
- src/main/resources/templates/workspace/wks-users.html
Fix issue#293. Add translate for email-palceholder at workspace->users to 'messages_en.properties' and 'messages_ru.properties'.
> [#293] Add russian translate to email-placeholder at workspace->users

- src/main/java/io/hexlet/typoreporter/controller/WorkspaceSettingsController.java
- src/test/java/io/hexlet/typoreporter/web/WorkspaceSettingsControllerIT.java
The workspace name is displayed correctly on the Integration page. One of the tests for checking the name of the space on the integration page has also been adjusted.
--
На странице integration корректно отображается имя рабочего пространства. Также скорретирован один из тестов для проверки имени пространства на странице "Интеграция".
> [#254] Add workspace name on Integration page (with test)

- src/main/resources/templates/fragments/footer.html
- src/main/resources/templates/fragments/panels.html
I checked once again overall application style and propose to improve it a little bit. Now the contrast is too high between navbar, content and footer. It's dark-light-dark now. Usually dark part only one - navbar or footer. So, I propose to make footer light. I think it will look better. By the way, this color scheme is in the file "landing.html", I just didn't implemented it fully when I did previous PR.
Current color scheme:
Proposed color scheme (from "landing.html"):
Demo: https://hexlet-correction-4.onrender.com/
> [#153] Add footer to website templates
